# Generated by Django 3.2.12 on 2022-03-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='receiver',
        ),
        migrations.AddField(
            model_name='donation',
            name='audit',
            field=models.BooleanField(default=False),
        ),
    ]
