# Generated by Django 3.2.12 on 2022-03-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_location', to='campaign.recieverlocation'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='raised_ammount',
            field=models.IntegerField(default=0),
        ),
    ]
