# Generated by Django 3.2.12 on 2022-03-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_auto_20220309_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='raised_ammount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_ammount',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
