# Generated by Django 3.2.12 on 2022-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20220310_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
