# Generated by Django 3.2.12 on 2022-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_alter_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieverlocation',
            name='lat',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='recieverlocation',
            name='lon',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
