# Generated by Django 3.2.12 on 2022-03-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20220310_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='raised_ammount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_ammount',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='recieverlocation',
            name='lat',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='recieverlocation',
            name='lon',
            field=models.DecimalField(db_index=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
